[variables]
PHP_VERSION = "8.2"

[phases.install]
cmds = ["composer update --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = ["php artisan config:clear", "php artisan view:cache"]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"
